#! /bin/tcsh -f
#This code makes an ensemble of CLM site instances. 

setenv CODENAME clm5.0_mar18/
setenv NAME FACE_ENSEMBLE_TRANSIENT_
set niter=5
set nparam=15
set p=1
set nsites=4
set BASEBUILD=CLM5_1x1pt_US-ORN_ens_PI00
set BASEYEAR=101
set PARAMROOT='/glade/u/home/rfisher/Matlab/pft_files/FACE_CLM_params/FACE_CLM_params_jan18_pi'
set RESTARTCASES=('CLM5_SPR_SPIN_.1x1pt_Br-cax' 'CLM5_SPR_SPIN_.bci_0.1x0.1_v4.0i' 'CLM5_ORNL.1521596285')
set SITENAMES=('1x1pt_Br-cax' 'bci_0.1x0.1_v4.0i' '1x1pt_US-ORN')

set s=1
while ($s<$nsites)
       set BASECASE=CLM5_$SITENAMES[$s]_ens_PI00 
  
       setenv EXPTNAME CLM5_$SITENAMES[$s]_ens_transient_PI00
       cd  /glade/p/work/rfisher/git/$CODENAME
       cd cime/scripts
       cd BCI_SENS_TEST

       pwd

       cd $EXPTNAME


       ./xmlchange RESUBMIT=2
       ./xmlchange EXEROOT="/glade/scratch/rfisher/$BASEBUILD/bld/"
       ./xmlchange BUILD_COMPLETE="TRUE"
       ./xmlchange CLM_CO2_TYPE=diagnostic
       ./xmlchange RUN_STARTDATE=1765-01-01
       #./xmlchange JOB_QUEUE=share
       #./xmlchange MAX_TASKS_PER_NODE=1
       #./xmlchange MPILIB=mpi-serial

      # set uclm="fsurdat='/glade/u/home/rfisher/single_point_drivers/$SITENAMES[$s]/surfdata_$SITENAMES[$s].nc'\nfinidat='/glade/scratch/rfisher/archive/$BASECASE/rest/0$BASEYEAR-01-01-00000/$BASECASE.clm2.r.0$BASEYEAR-01-01-00000.nc'"
      set uclm="fsurdat='/glade/u/home/rfisher/single_point_drivers/$SITENAMES[$s]/surfdata_$SITENAMES[$s].nc'\nfinidat='/glade/scratch/rfisher/$BASECASE/run/$BASECASE.clm2.r.0$BASEYEAR-01-01-00000.nc'"
      echo  $uclm >user_nl_clm

        cp /glade/u/home/rfisher/clm_case_scripts/user_nl_datm_FACE_transient user_nl_datm
        cp /glade/u/home/rfisher/clm_case_scripts/datm.streams.txt.co2tseries_control_newformat /glade/scratch/rfisher/$EXPTNAME/run/datm.streams.txt.co2tseries      

       ./case.submit
@ s ++
end

    
