#!/bin/sh
# =======================================================================================
#
# This script will create, setup and build a single-site simulation at
# Barro Colorado Island, Panama
#
# A specialized domain and surface file was generated using Gautam Bisht's
# "matlab-script-for-clm-sparse-grid".
#
# Meteorological driving data was prepared using Ryan Knox's "ConvertMetCSVtoCLM".
# PLEASE SEE THE DRIVER DATA'S METADATA FOR ACKNOWLEDGMENTS AND ATTRIBUTION
#
# In this implementation, meteorological data will be cycled based on the data
# offsets.  We make use of "CLM1PT" datm mode, and make a minor modification to the
# default stream-file to signal to CLM/ELM that no downwelling long-wave is available
# in our dataset.
#
# The base-version of this script, works off the assumption that driver data
# and surface/domain data have been unpacked in the cime/scripts directory
# and can all be found in a parent directory with alias $SITE_DIR
#
#
# Ryan Knox (Mon Nov 13 13:53:03 PST 2017)
# Updated to 14 year BCI record Nov 14
#
# --- Modified by Shawn Serbin to run on Modex with CTSM HLM
#
# USER SETTINGS
# USER MAY ALSO WANT TO ADJUST XML CHANGES, AND NAMELIST ARGUMENTS
# =======================================================================================

export MODEL_SOURCE=/glade/p/work/rfisher/git/clm5.0_mar18   # CTSM/CLM/ELM source directory
export SITE_NAME=bci_0.1x0.1_v4.0i                           # Name of folder with site data
export SITE_BASE_DIR=/glade/u/home/rfisher/CTSM-FATES_inputs # Where is the site folder located? (SITE_NAME)
export TAG='CLM5-pf1'                                         # User defined tag to differentiate runs
export COMPSET=2000_DATM%1PT_CLM50%BGC_SICE_SOCN_RTM_SGLC_SWAV
export RES=CLM_USRDAT
export MAC=cheyenne                                          # Name your machine
export COMPILER=gnu                                          # Name your compiler
export CASEROOT=/glade/p/work/rfisher/git/clm5.0_mar18/cime/scripts                       # Where the build is generated (probably on scratch partition)
export CLM_USRDAT_DOMAIN=domain_bci_sparse_grid_c180227.nc   # Name of domain file in scripts/${SITE_DIR}/
export CLM_USRDAT_SURDAT=surfdata_bci_sparse_grid_c180227.nc # Name of surface file in scripts/${SITE_DIR}/

# Set FATES parameter path and param file here:
# DEPENDENT PATHS AND VARIABLES (USER MIGHT CHANGE THESE..)
# =======================================================================================

date_var=$(date +%s)
export CLM_SURFDAT_DIR=${SITE_BASE_DIR}/${SITE_NAME}
export CLM_DOMAIN_DIR=${SITE_BASE_DIR}/${SITE_NAME}
export DIN_LOC_ROOT_FORCE=${SITE_BASE_DIR}
export CLM_HASH=`(cd ${MODEL_SOURCE};git log -n 1 --pretty=%h)`
FATES_HASH=`(cd ${MODEL_SOURCE}/src/fates;git log -n 1 --pretty=%h)`
export GIT_HASH=C${CLM_HASH}-F${FATES_HASH}
CASE_NAME=${CASEROOT}/${TAG}.${COMPSET}.${MAC}.${GIT_HASH}.${date_var}
echo "CREATING NEW CASE IN "${CASE_NAME}
export CASEN=${TAG}.${COMPSET}.${MAC}.${GIT_HASH}.${date_var}
# export USRDAT_METFORCE_NAME=${SITE_DIR} (DEPRECATED?)

# REMOVE EXISTING CASE IF PRESENT
rm -r ${CASE_NAME}

# CREATE THE CASE
cd ${MODEL_SOURCE}/cime/scripts/
echo $PWD
echo "Running with HLM-FATES location: "${MODEL_SOURCE}
./create_newcase --case ${CASE_NAME} --res ${RES} --compset ${COMPSET} --mach ${MAC}  --run-unsupported

echo "*** Move to case directory ***"
cd ${CASE_NAME}
echo $PWD


# SET PATHS TO SCRATCH ROOT, DOMAIN AND MET DATA (USERS WILL PROB NOT CHANGE THESE)
# =================================================================================
# Modify XMLs
echo *** Modifying XMLs ***
./xmlchange --file env_run.xml --id ATM_DOMAIN_FILE --val ${CLM_USRDAT_DOMAIN}
echo "*** Changing ATM domain to ${CLM_USRDAT_DOMAIN}"
./xmlchange --file env_run.xml --id ATM_DOMAIN_PATH --val ${CLM_DOMAIN_DIR}
./xmlchange --file env_run.xml --id LND_DOMAIN_FILE --val ${CLM_USRDAT_DOMAIN}
echo "*** Changing LND domain to ${CLM_USRDAT_DOMAIN}"
./xmlchange --file env_run.xml --id LND_DOMAIN_PATH --val ${CLM_DOMAIN_DIR}
./xmlchange --file env_run.xml --id DATM_MODE --val CLM1PT
./xmlchange --file env_run.xml --id CLM_USRDAT_NAME --val ${SITE_NAME}
./xmlchange --file env_run.xml --id DIN_LOC_ROOT_CLMFORC --val ${DIN_LOC_ROOT_FORCE}
# Set run location to case dir
#./xmlchange --file env_build.xml --id CIME_OUTPUT_ROOT --val ${CASE_NAME}
#./xmlchange --file env_build.xml --id CIME_OUTPUT_ROOT --val model_output

# SPECIFY PE LAYOUT FOR SINGLE SITE RUN (USERS WILL PROB NOT CHANGE THESE)
# =================================================================================

./xmlchange NTASKS_ATM=1
./xmlchange NTASKS_CPL=1
./xmlchange NTASKS_GLC=1
./xmlchange NTASKS_OCN=1
./xmlchange NTASKS_WAV=1
./xmlchange NTASKS_ICE=1
./xmlchange NTASKS_LND=1
./xmlchange NTASKS_ROF=1
./xmlchange NTASKS_ESP=1
./xmlchange ROOTPE_ATM=0
./xmlchange ROOTPE_CPL=0
./xmlchange ROOTPE_GLC=0
./xmlchange ROOTPE_OCN=0
./xmlchange ROOTPE_WAV=0
./xmlchange ROOTPE_ICE=0
./xmlchange ROOTPE_LND=0
./xmlchange ROOTPE_ROF=0
./xmlchange ROOTPE_ESP=0
./xmlchange NTHRDS_ATM=1
./xmlchange NTHRDS_CPL=1
./xmlchange NTHRDS_GLC=1
./xmlchange NTHRDS_OCN=1
./xmlchange NTHRDS_WAV=1
./xmlchange NTHRDS_ICE=1
./xmlchange NTHRDS_LND=1
./xmlchange NTHRDS_ROF=1
./xmlchange NTHRDS_ESP=1

# SPECIFY RUN TYPE PREFERENCES (USERS WILL CHANGE THESE)
# =================================================================================
./xmlchange --id DEBUG --val FALSE
./xmlchange --id STOP_N --val 5
./xmlchange --id RUN_STARTDATE --val '2006-06-01'
./xmlchange --id STOP_OPTION --val nyears
#./xmlchange --id CLM_FORCE_COLDSTART --val on  #./xmlchange --id CLM_FORCE_COLDSTART --val on  # use cold start??
./xmlchange --id RESUBMIT --val 13
./xmlchange --id DATM_CLMNCEP_YR_START --val 2003
./xmlchange --id DATM_CLMNCEP_YR_END --val 2016

# MACHINE SPECIFIC, AND/OR USER PREFERENCE CHANGES (USERS WILL CHANGE THESE)
# =================================================================================

#./xmlchange --file env_run.xml --id DOUT_S_SAVE_INTERIM_RESTART_FILES --val TRUE
#./xmlchange --file env_run.xml --id DOUT_S --val TRUE
#./xmlchange --file env_run.xml --id DOUT_S_ROOT --val '$CASEROOT/run'
#./xmlchange --file env_run.xml --id RUNDIR --val ${CASE_NAME}/run
#./xmlchange --file env_build.xml --id EXEROOT --val ${CASE_NAME}/bld


# MODIFY THE CLM NAMELIST (USERS MODIFY AS NEEDED)
echo "*** FATES inventory list file: ${SITE_BASE_DIR}/${SITE_NAME}/bci_inv_file_list.txt ***"
cat >> user_nl_clm <<EOF
fsurdat = '${CLM_SURFDAT_DIR}/${CLM_USRDAT_SURDAT}'
EOF

# Usefull user_nl_clm arguments:
# This couplet will enable hourly output
# hist_mfilt             = 480
# hist_nhtfrq            = -1
# hist_fincl1='NEP','NPP','GPP','TLAI','TSOI_10CM','QVEGT','EFLX_LH_TOT','AR','HR','ED_biomass','ED_bleaf','ED_balive','DDBH_SCPF','BA_SCPF','NPLANT_SCPF','M1_SCPF','M2_SCPF','M3_SCPF','M4_SCPF','M5_SCPF','M6_SCPF','WIND','ZBOT','FSDS','RH','TBOT','PBOT','QBOT','RAIN','FLDS'

# MODIFY THE DATM NAMELIST (DANGER ZONE - USERS BEWARE CHANGING)

cat >> user_nl_datm <<EOF
taxmode = "cycle", "cycle", "cycle"
EOF

echo "*** Setup Case ***"
echo " "
./case.setup

echo "*** Update FATES param file ***"
echo " "
cat >> user_nl_clm <<EOF
fates_paramfile = "${CASE_NAME}/${FATES_PARAM_FILE}"
EOF

# HERE WE NEED TO MODIFY THE STREAM FILE (DANGER ZONE - USERS BEWARE CHANGING)
# MAY WANT TO UPDATE THIS TO REMOVE FIXED DIR LINK TO CASEROOT/run
./preview_namelists
cp /glade/scratch/rfisher/$CASEN/run/datm.streams.txt.CLM1PT.CLM_USRDAT user_datm.streams.txt.CLM1PT.CLM_USRDAT
`sed -i '/FLDS/d' user_datm.streams.txt.CLM1PT.CLM_USRDAT`

cat user_datm.streams.txt.CLM1PT.CLM_USRDAT

echo "*** Build Case ***"
./case.build

echo "*** Submit ***"
./case.submit
