#! /bin/tcsh -f
setenv CODENAME clm5.0_mar18/
setenv NAME FACE_BCI_
set niter=5
set nparam=15
set p=1
set BASEYEAR=2071
set BASECASE=CLM5-pf1.2000_DATM%1PT_CLM50%BGC_SICE_SOCN_RTM_SGLC_SWAV.cheyenne.Cedd59ca-F52bad28.1521489651

while ($p<$nparam)
set x=1
while ($x<$niter)

setenv EXPTNAME CLM5_BCI_FACE_sens_ens_PI$p$x
set echo

cd  /glade/p/work/rfisher/git/$CODENAME

cd cime/scripts
cd BCI_SENS_TEST
pwd

cd $EXPTNAME

./xmlchange RESUBMIT=2
./xmlchange CCSM_CO2_PPMV=287
./xmlchange JOB_QUEUE=share
./xmlchange MAX_TASKS_PER_NODE=1
./xmlchange MPILIB=mpi-serial
#./case.setup --reset
./xmlchange BUILD_COMPLETE=TRUE
./xmlchange JOB_WALLCLOCK_TIME=05:45:00

set uclm="fsurdat='/glade/u/home/rfisher/CTSM-FATES_inputs/bci_0.1x0.1_v4.0i/surfdata_bci_sparse_grid_c180227.nc'\nfinidat='/glade/scratch/rfisher/$BASECASE/run/$BASECASE.clm2.r.$BASEYEAR-06-01-00000.nc'\nparamfile='/glade/u/home/rfisher/Matlab/pft_files/FACE_CLM_params/FACE_CLM_params_jan18_pi$p$x.nc'"
echo  $uclm >user_nl_clm

cat user_nl_clm

./case.setup

#./case.build
./case.submit
@ x ++
end
@ p ++
end
    
